### ISSUE TITLE
Feature request: make mesh more amenable to other Julia datatypes?

### ISSUE THREAD

**Issue by Ickaser** [JuliaGeometry/MarchingCubes.jl#7]
One of the reasons I want to use this module is to be able to put together a pure-Julia data pipeline for micro-CT data. To that end, it would be helpful if I could take the mesh generated by this project, and pull it over to Makie.jl or some other Julia plotting software. 

It seems to me like it shouldn't be too difficult to modify the code base to use Triangles from [GeometryBasics.jl ](https://github.com/JuliaGeometry/GeometryBasics.jl) , then make the mesh compatible with [Meshes.jl](https://github.com/JuliaGeometry/Meshes.jl) and therefore [MeshViz](https://github.com/JuliaGeometry/MeshViz.jl) .

I can help with this, I think (although maybe not very fast).

**Comment by t-bltg** [comment]
Hi,

I'm a bit puzzled on this one. The goal of this package was to be as light weight and universal as possible. This is why e.g. `PlyIO` is an optional `[extras]` dependency used only for the example scenario.

The representation using vertices, triangles and normals is quite universal, uses standard `Julia` types and pretty common `StaticArrays`, whereas `GeometryBasics` is already a level upwards in the abstraction, and oriented towards `Makie.jl`.

This package was written for https://github.com/JuliaPlots/UnicodePlots.jl, specifically for [`isosurface`](https://github.com/JuliaPlots/UnicodePlots.jl#isosurface-plot), and since we're not using `GeometryBasics` there, I don't see a reason to add extra dependencies (they will just pile up with more and more maintenance needed, e.g. when `GeometryTypes` was superseded by `GeometryBasics`).

Why not write a conversion method which maps vertices and triangles to `GeometryBasics` types (should be relatively straightforward) instead of modifying the internal algorithm types ? We can add it to `README.md` as an example application if you wish ...

**Comment by Ickaser** [comment]
That seems like a good way forward to me. I can start digging through to try and put something together.

**Comment by t-bltg** [comment]
We can eventually support `GeometryBasics` in the (optional) way I dealt with `PlyIO`(even if this is non standard), by passing the module to the function, as in `example.jl`:
https://github.com/JuliaGeometry/MarchingCubes.jl/blob/d2ed53aba364e1be9a1471527da74bb9fb126867/src/example.jl#L55
